// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HIMsg.proto

package com.evsward.butler.entities.protobuf;

public final class HIMessage {
  private HIMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HIReqMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HIReqMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *请求消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonReqMsg = 1;</code>
     */
    boolean hasJsonReqMsg();
    /**
     * <pre>
     *请求消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonReqMsg = 1;</code>
     */
    java.lang.String getJsonReqMsg();
    /**
     * <pre>
     *请求消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonReqMsg = 1;</code>
     */
    com.google.protobuf.ByteString
        getJsonReqMsgBytes();
  }
  /**
   * <pre>
   *请求协议
   * </pre>
   *
   * Protobuf type {@code HIReqMessage}
   */
  public  static final class HIReqMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HIReqMessage)
      HIReqMessageOrBuilder {
    // Use HIReqMessage.newBuilder() to construct.
    private HIReqMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HIReqMessage() {
      jsonReqMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HIReqMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              jsonReqMsg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIReqMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIReqMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage.class, com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage.Builder.class);
    }

    private int bitField0_;
    public static final int JSONREQMSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object jsonReqMsg_;
    /**
     * <pre>
     *请求消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonReqMsg = 1;</code>
     */
    public boolean hasJsonReqMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *请求消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonReqMsg = 1;</code>
     */
    public java.lang.String getJsonReqMsg() {
      java.lang.Object ref = jsonReqMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jsonReqMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *请求消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonReqMsg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJsonReqMsgBytes() {
      java.lang.Object ref = jsonReqMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonReqMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasJsonReqMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonReqMsg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonReqMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage)) {
        return super.equals(obj);
      }
      com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage other = (com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage) obj;

      boolean result = true;
      result = result && (hasJsonReqMsg() == other.hasJsonReqMsg());
      if (hasJsonReqMsg()) {
        result = result && getJsonReqMsg()
            .equals(other.getJsonReqMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasJsonReqMsg()) {
        hash = (37 * hash) + JSONREQMSG_FIELD_NUMBER;
        hash = (53 * hash) + getJsonReqMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求协议
     * </pre>
     *
     * Protobuf type {@code HIReqMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HIReqMessage)
        com.evsward.butler.entities.protobuf.HIMessage.HIReqMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIReqMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIReqMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage.class, com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage.Builder.class);
      }

      // Construct using com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        jsonReqMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIReqMessage_descriptor;
      }

      public com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage getDefaultInstanceForType() {
        return com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage.getDefaultInstance();
      }

      public com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage build() {
        com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage buildPartial() {
        com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage result = new com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jsonReqMsg_ = jsonReqMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage) {
          return mergeFrom((com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage other) {
        if (other == com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage.getDefaultInstance()) return this;
        if (other.hasJsonReqMsg()) {
          bitField0_ |= 0x00000001;
          jsonReqMsg_ = other.jsonReqMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJsonReqMsg()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object jsonReqMsg_ = "";
      /**
       * <pre>
       *请求消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonReqMsg = 1;</code>
       */
      public boolean hasJsonReqMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *请求消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonReqMsg = 1;</code>
       */
      public java.lang.String getJsonReqMsg() {
        java.lang.Object ref = jsonReqMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jsonReqMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *请求消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonReqMsg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJsonReqMsgBytes() {
        java.lang.Object ref = jsonReqMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonReqMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *请求消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonReqMsg = 1;</code>
       */
      public Builder setJsonReqMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jsonReqMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonReqMsg = 1;</code>
       */
      public Builder clearJsonReqMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jsonReqMsg_ = getDefaultInstance().getJsonReqMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *请求消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonReqMsg = 1;</code>
       */
      public Builder setJsonReqMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jsonReqMsg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HIReqMessage)
    }

    // @@protoc_insertion_point(class_scope:HIReqMessage)
    private static final com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage();
    }

    public static com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HIReqMessage>
        PARSER = new com.google.protobuf.AbstractParser<HIReqMessage>() {
      public HIReqMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HIReqMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HIReqMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HIReqMessage> getParserForType() {
      return PARSER;
    }

    public com.evsward.butler.entities.protobuf.HIMessage.HIReqMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HIAckMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HIAckMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *响应消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonAckMsg = 1;</code>
     */
    boolean hasJsonAckMsg();
    /**
     * <pre>
     *响应消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonAckMsg = 1;</code>
     */
    java.lang.String getJsonAckMsg();
    /**
     * <pre>
     *响应消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonAckMsg = 1;</code>
     */
    com.google.protobuf.ByteString
        getJsonAckMsgBytes();
  }
  /**
   * <pre>
   *返回协议
   * </pre>
   *
   * Protobuf type {@code HIAckMessage}
   */
  public  static final class HIAckMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HIAckMessage)
      HIAckMessageOrBuilder {
    // Use HIAckMessage.newBuilder() to construct.
    private HIAckMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HIAckMessage() {
      jsonAckMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HIAckMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              jsonAckMsg_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIAckMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIAckMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage.class, com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage.Builder.class);
    }

    private int bitField0_;
    public static final int JSONACKMSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object jsonAckMsg_;
    /**
     * <pre>
     *响应消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonAckMsg = 1;</code>
     */
    public boolean hasJsonAckMsg() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *响应消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonAckMsg = 1;</code>
     */
    public java.lang.String getJsonAckMsg() {
      java.lang.Object ref = jsonAckMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jsonAckMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *响应消息json格式的字符串
     * </pre>
     *
     * <code>required string jsonAckMsg = 1;</code>
     */
    public com.google.protobuf.ByteString
        getJsonAckMsgBytes() {
      java.lang.Object ref = jsonAckMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonAckMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasJsonAckMsg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonAckMsg_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonAckMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage)) {
        return super.equals(obj);
      }
      com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage other = (com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage) obj;

      boolean result = true;
      result = result && (hasJsonAckMsg() == other.hasJsonAckMsg());
      if (hasJsonAckMsg()) {
        result = result && getJsonAckMsg()
            .equals(other.getJsonAckMsg());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasJsonAckMsg()) {
        hash = (37 * hash) + JSONACKMSG_FIELD_NUMBER;
        hash = (53 * hash) + getJsonAckMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *返回协议
     * </pre>
     *
     * Protobuf type {@code HIAckMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HIAckMessage)
        com.evsward.butler.entities.protobuf.HIMessage.HIAckMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIAckMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIAckMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage.class, com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage.Builder.class);
      }

      // Construct using com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        jsonAckMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.evsward.butler.entities.protobuf.HIMessage.internal_static_HIAckMessage_descriptor;
      }

      public com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage getDefaultInstanceForType() {
        return com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage.getDefaultInstance();
      }

      public com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage build() {
        com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage buildPartial() {
        com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage result = new com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.jsonAckMsg_ = jsonAckMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage) {
          return mergeFrom((com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage other) {
        if (other == com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage.getDefaultInstance()) return this;
        if (other.hasJsonAckMsg()) {
          bitField0_ |= 0x00000001;
          jsonAckMsg_ = other.jsonAckMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasJsonAckMsg()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object jsonAckMsg_ = "";
      /**
       * <pre>
       *响应消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonAckMsg = 1;</code>
       */
      public boolean hasJsonAckMsg() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *响应消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonAckMsg = 1;</code>
       */
      public java.lang.String getJsonAckMsg() {
        java.lang.Object ref = jsonAckMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jsonAckMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *响应消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonAckMsg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getJsonAckMsgBytes() {
        java.lang.Object ref = jsonAckMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonAckMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *响应消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonAckMsg = 1;</code>
       */
      public Builder setJsonAckMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jsonAckMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *响应消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonAckMsg = 1;</code>
       */
      public Builder clearJsonAckMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        jsonAckMsg_ = getDefaultInstance().getJsonAckMsg();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *响应消息json格式的字符串
       * </pre>
       *
       * <code>required string jsonAckMsg = 1;</code>
       */
      public Builder setJsonAckMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        jsonAckMsg_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HIAckMessage)
    }

    // @@protoc_insertion_point(class_scope:HIAckMessage)
    private static final com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage();
    }

    public static com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HIAckMessage>
        PARSER = new com.google.protobuf.AbstractParser<HIAckMessage>() {
      public HIAckMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HIAckMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HIAckMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HIAckMessage> getParserForType() {
      return PARSER;
    }

    public com.evsward.butler.entities.protobuf.HIMessage.HIAckMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HIReqMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HIReqMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HIAckMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HIAckMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013HIMsg.proto\"\"\n\014HIReqMessage\022\022\n\njsonReq" +
      "Msg\030\001 \002(\t\"\"\n\014HIAckMessage\022\022\n\njsonAckMsg\030" +
      "\001 \002(\tB1\n$com.evsward.butler.entities.pro" +
      "tobufB\tHIMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HIReqMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HIReqMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HIReqMessage_descriptor,
        new java.lang.String[] { "JsonReqMsg", });
    internal_static_HIAckMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HIAckMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HIAckMessage_descriptor,
        new java.lang.String[] { "JsonAckMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
